#!/usr/bin/env bash
# create a backup of the original hosts file
cp /etc/hosts /etc/hosts.bak
# configure localhost resolves to 127.0.0.2
sed -i 's/127.0.0.1/127.0.0.2' /etc/hosts.bak
# configure facebook.com resolves to 8.8.8.8
echo "8.8.8.8 facebook.com" >> /etc/hosts.bak

cp -f /etc/hosts.bak /etc/hosts
